package com.ntian.music.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.ntian.music.greendao.MusicMenu;
import com.ntian.music.greendao.MusicMenuDetail;

import com.ntian.music.greendao.MusicMenuDao;
import com.ntian.music.greendao.MusicMenuDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig musicMenuDaoConfig;
    private final DaoConfig musicMenuDetailDaoConfig;

    private final MusicMenuDao musicMenuDao;
    private final MusicMenuDetailDao musicMenuDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        musicMenuDaoConfig = daoConfigMap.get(MusicMenuDao.class).clone();
        musicMenuDaoConfig.initIdentityScope(type);

        musicMenuDetailDaoConfig = daoConfigMap.get(MusicMenuDetailDao.class).clone();
        musicMenuDetailDaoConfig.initIdentityScope(type);

        musicMenuDao = new MusicMenuDao(musicMenuDaoConfig, this);
        musicMenuDetailDao = new MusicMenuDetailDao(musicMenuDetailDaoConfig, this);

        registerDao(MusicMenu.class, musicMenuDao);
        registerDao(MusicMenuDetail.class, musicMenuDetailDao);
    }
    
    public void clear() {
        musicMenuDaoConfig.getIdentityScope().clear();
        musicMenuDetailDaoConfig.getIdentityScope().clear();
    }

    public MusicMenuDao getMusicMenuDao() {
        return musicMenuDao;
    }

    public MusicMenuDetailDao getMusicMenuDetailDao() {
        return musicMenuDetailDao;
    }

}
