package com.ntian.music.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MUSIC_MENU.
 */
public class MusicMenu {

    private Long id;
    private String MenuName;
    private java.util.Date AddTime;
    private Integer MusicItems;

    public MusicMenu() {
    }

    public MusicMenu(Long id) {
        this.id = id;
    }

    public MusicMenu(Long id, String MenuName, java.util.Date AddTime, Integer MusicItems) {
        this.id = id;
        this.MenuName = MenuName;
        this.AddTime = AddTime;
        this.MusicItems = MusicItems;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMenuName() {
        return MenuName;
    }

    public void setMenuName(String MenuName) {
        this.MenuName = MenuName;
    }

    public java.util.Date getAddTime() {
        return AddTime;
    }

    public void setAddTime(java.util.Date AddTime) {
        this.AddTime = AddTime;
    }

    public Integer getMusicItems() {
        return MusicItems;
    }

    public void setMusicItems(Integer MusicItems) {
        this.MusicItems = MusicItems;
    }

}
