package com.ntian.music.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MUSIC_MENU_DETAIL.
 */
public class MusicMenuDetail {

    private Long id;
    private String Title;
    private String TitlePinyin;
    private String Singer;
    private String MusicPath;
    private Long Base_ID;
    private String MenuName;
    private java.util.Date MenuCreateTime;

    public MusicMenuDetail() {
    }

    public MusicMenuDetail(Long id) {
        this.id = id;
    }

    public MusicMenuDetail(Long id, String Title, String TitlePinyin, String Singer, String MusicPath, Long Base_ID, String MenuName, java.util.Date MenuCreateTime) {
        this.id = id;
        this.Title = Title;
        this.TitlePinyin = TitlePinyin;
        this.Singer = Singer;
        this.MusicPath = MusicPath;
        this.Base_ID = Base_ID;
        this.MenuName = MenuName;
        this.MenuCreateTime = MenuCreateTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getTitlePinyin() {
        return TitlePinyin;
    }

    public void setTitlePinyin(String TitlePinyin) {
        this.TitlePinyin = TitlePinyin;
    }

    public String getSinger() {
        return Singer;
    }

    public void setSinger(String Singer) {
        this.Singer = Singer;
    }

    public String getMusicPath() {
        return MusicPath;
    }

    public void setMusicPath(String MusicPath) {
        this.MusicPath = MusicPath;
    }

    public Long getBase_ID() {
        return Base_ID;
    }

    public void setBase_ID(Long Base_ID) {
        this.Base_ID = Base_ID;
    }

    public String getMenuName() {
        return MenuName;
    }

    public void setMenuName(String MenuName) {
        this.MenuName = MenuName;
    }

    public java.util.Date getMenuCreateTime() {
        return MenuCreateTime;
    }

    public void setMenuCreateTime(java.util.Date MenuCreateTime) {
        this.MenuCreateTime = MenuCreateTime;
    }

}
