package com.ntian.greendaodb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table VIDEO_SCAN_RECORDS.
 */
public class VideoScanRecords {

    private Long id;
    private Long Base_ID;
    private Boolean Is_Scanned;
    private Long PlayedPosition;
    private java.util.Date Last_Played;

    public VideoScanRecords() {
    }

    public VideoScanRecords(Long id) {
        this.id = id;
    }

    public VideoScanRecords(Long id, Long Base_ID, Boolean Is_Scanned, Long PlayedPosition, java.util.Date Last_Played) {
        this.id = id;
        this.Base_ID = Base_ID;
        this.Is_Scanned = Is_Scanned;
        this.PlayedPosition = PlayedPosition;
        this.Last_Played = Last_Played;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getBase_ID() {
        return Base_ID;
    }

    public void setBase_ID(Long Base_ID) {
        this.Base_ID = Base_ID;
    }

    public Boolean getIs_Scanned() {
        return Is_Scanned;
    }

    public void setIs_Scanned(Boolean Is_Scanned) {
        this.Is_Scanned = Is_Scanned;
    }

    public Long getPlayedPosition() {
        return PlayedPosition;
    }

    public void setPlayedPosition(Long PlayedPosition) {
        this.PlayedPosition = PlayedPosition;
    }

    public java.util.Date getLast_Played() {
        return Last_Played;
    }

    public void setLast_Played(java.util.Date Last_Played) {
        this.Last_Played = Last_Played;
    }

}
