package com.ntian.videoplayer.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table MUSIC_MENU_DETAIL.
 */
public class MusicMenuDetail {

    private Long id;
    private String Title;
    private String TitlePinyin;
    private String Singer;
    private String path;
    private Long Base_ID;
    private String musicmenu;

    public MusicMenuDetail() {
    }

    public MusicMenuDetail(Long id) {
        this.id = id;
    }

    public MusicMenuDetail(Long id, String Title, String TitlePinyin, String Singer, String path, Long Base_ID, String musicmenu) {
        this.id = id;
        this.Title = Title;
        this.TitlePinyin = TitlePinyin;
        this.Singer = Singer;
        this.path = path;
        this.Base_ID = Base_ID;
        this.musicmenu = musicmenu;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return Title;
    }

    public void setTitle(String Title) {
        this.Title = Title;
    }

    public String getTitlePinyin() {
        return TitlePinyin;
    }

    public void setTitlePinyin(String TitlePinyin) {
        this.TitlePinyin = TitlePinyin;
    }

    public String getSinger() {
        return Singer;
    }

    public void setSinger(String Singer) {
        this.Singer = Singer;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getBase_ID() {
        return Base_ID;
    }

    public void setBase_ID(Long Base_ID) {
        this.Base_ID = Base_ID;
    }

    public String getMusicmenu() {
        return musicmenu;
    }

    public void setMusicmenu(String musicmenu) {
        this.musicmenu = musicmenu;
    }

}
